### ISSUE TITLE
Video Player Transparency Cuased by Projection or Cone Emission.

### ISSUE THREAD

**Issue by realHachiDog** [AcChosen/VR-Stage-Lighting#1]
Hi!

I'm working ona World for a community and during the process  I made a Drinking bar with a video player material on it. I have 2 Pan light (Audio Link Version) above the bar. When the light projection/cone hits the surface of the bar the faces of the other side of the mesh comes visible temporaly throught the video player face.

There is any solution for that or am i doing something really wrong?

For Video player i'm using the same material you provided for the demo scene. I tried other materials/shaders and settings but all of them had the same issue.

The mesh is static and use Bakery Standard Material.

![ScreenShot_20210601211051](https://user-images.githubusercontent.com/67958965/120377787-de8a3700-c31d-11eb-9a2f-628e08915b28.png)

**Comment by AcChosen** [comment]
Hello, sorry for the late reply!

From what I'm seeing, I think this is a depth sorting issue.

The material/shader you're using doesn't support depth, most purely "unlit" shaders do not. A shader that supports depth is one that has a shadow caster pass. Try using a regular unity standard material with the emission feature turned on.

The materials I provided for the screen example scene were pure to demonstrate the ability to read DMXand such, I'll upload a more appropriate material soon that's more friendly with the lights.

**Comment by AcChosen** [comment]
Another option is to try to put a plane with a standard material on behind the screen!
This should allow you to use the same material regardless!

**Comment by realHachiDog** [comment]
Hi!

Thanks for the replay! I will try the given solutions you mentioned and i will get back to you.
Also can you give bit more details on how to use the color sampling from render material for the lights? because i seen the check mark on the shader but where should i tell the shader which render material he supossed to sample from.

Thanks for the answers and for the amezing work you did with this project! Its gona change the future party worlds for sure!
