### ISSUE TITLE
VRSL-AudioLink-Static-Lightbar breaks with latest version of AudioLink

### ISSUE THREAD

**Issue by seanidzenga** [AcChosen/VR-Stage-Lighting#3]
I recently upgraded to AudioLink v2.7.0 and the VRSL-AudioLink-Static-Lightbar prefabs have turned bright red.

![image](https://user-images.githubusercontent.com/3802836/144912658-bb51f970-d364-4296-8f3d-e83a3f8728f1.png)

**Comment by cnlohr** [comment]
Any idea what is going on here?

**Comment by AcChosen** [comment]
Working on it, will update soon

**Comment by seanidzenga** [comment]
An unrelated issue with my world had me reimport audiolink, udonsharp, etc and now it's looking normal so I think this can be closed as a BCAK error

**Comment by dEVtHArEV** [comment]
I am having this issue what was the solution here?
