### ISSUE TITLE
[Feature] Build "Photosensitive Mode" into Default Controls

### ISSUE THREAD

**Issue by BusterNeece** [AcChosen/VR-Stage-Lighting#32]
Hello!

Many of us in the VR community take to VR specifically because, for one reason or another, we can't enjoy the real-world equivalents of the things we're doing in VR. For myself and many folks like me, that includes the IRL club scene, which we can't partake in because the strobes cause us anything from discomfort to headaches and, in worst cases, seizures.

The club worlds in VR offer us a great opportunity to experience the music, the stunning visuals and the sense of community that comes from clubs, without necessarily endangering ourselves with strobing lights. Unfortunately, I think many world builders are content just putting a disclaimer near the front of their world telling folks like me to just avoid the world entirely, rather than putting in the work to allow us to experience a majority of the club "vibe", just without the strobing lights.

While I am a software dev myself and I am tech-savvy, let me preface this next bit by saying I'm not familiar with VRSL's implementation specifics or its limitations myself.

However, I've been told that in VRSL we actually have an opportunity to accommodate folks with this condition rather easily. It's my understanding that there is a separate "strobe" signal sent as part of the data stream that VRSL uses, and that by building a setting that simply ignores that signal (or modifies the shader/texture/whatever used to do it to be effectively invisible), you could enable a "photosensitive mode" that would work across any instance that uses your tool set.

One of the biggest hurdles to improving accessibility in general is ease of adoption, so if something like this could be baked right into the prefabricated settings panel that VRSL ships with, it would offer world builders an accessible solution that works out of the box, requires no extra effort or thought on their part, and offers a perfect accommodation of photosensitive folks' needs without interfering in any way with other world users.

Please let me know if there's anything I can do to help facilitate this. I greatly appreciate the work you've done with VRSL, and I appreciate you taking the time to read this.

**Comment by ListenerJubatus** [comment]
I could see this done via a Strobe intensity slider

**Comment by towneh** [comment]
Yeah this is entirely doable but also still on the world creators to implement. One possibility is that we could encourage its use by creating a prefab. In the case where we ourselves build worlds using VRSL we also provided accessibility features for light-sensitive attendees (epilepsy etc)

**Comment by vesturo** [comment]
@AcChosen with you integrating the DMX Strobe toggle prefab and script this can be closed no? at least for animated audiolink lights it will be solely rely on the world maker to integrate a security feature, as it relys on their animations

**Comment by BusterNeece** [comment]
I consider the addition of the strobe toggle to the prefab to be an excellent solution. Hopefully world builders can update to the latest version and we can enjoy more worlds! Thank you @AcChosen for your work on this!
