### ISSUE TITLE
missing script

### ISSUE THREAD

**Issue by smitrowan** [AcChosen/VR-Stage-Lighting#4]
Hello anyone who is reading this
i would like to say i love how this system looks in Orion, is had inspired me to make a club. 
but sadly there are some problems whenever i use any of the versions of vr-stage-light, error codes here:
![Screenshot_1](https://user-images.githubusercontent.com/99358031/153268440-f9b5f83b-07cd-4c6d-aa13-64fa6a029fac.png)

im using the latest version's of audiolink, unity and udonsharp. and my focus in this pack is only the audiolink versions of the lights/lazer.

i have tried it with all the recomended packages but it will still have the same problem. the only thing that worked for me was using the branch made by unitycoder, but that one has some light glitches, where all the lights can be seen thru mesh

i would love it if someone could help me with this problem.
thx for reading.

**Comment by AcChosen** [comment]
Hello!
First question being, did you install VRSL with the included unitypackage file or by copying the repository directly? 
Also, are you in the correct version of Unity? (2019.4.31f)

**Comment by smitrowan** [comment]
i dragged the file into unity, i could not find a unitypackage, and yes the unity version is 2019.4.31f1

thx for the fast reaction

**Comment by AcChosen** [comment]
https://github.com/AcChosen/VR-Stage-Lighting/releases/tag/v1.20
This is latest release page for VRSL, it includes some guides as well as the appropriate unitypackage file (the 4th file from the top). 

Try installing VRSL with the unitypackage file and see if that handles your problems.

**Comment by smitrowan** [comment]
thank you so mutch!! ill try as soon as i can
