### ISSUE TITLE
Can't seem to find out how to make my lights change direction.

### ISSUE THREAD

**Issue by syntaxxl** [AcChosen/VR-Stage-Lighting#5]
The cards system also doesn't work. 
![image](https://user-images.githubusercontent.com/66563883/164956368-472993e3-26b9-4cc8-b366-098f34165b59.png)

The lights itself are working with audiolink just fine. Sorry if this isn't the place to post this, but I couldn't find anywhere else.

**Comment by syntaxxl** [comment]
Actually, the lights are only working when I'm in Desktop mode. 
![image](https://user-images.githubusercontent.com/66563883/164958617-059ddc4b-ba35-463b-aa94-0a937ce4fa8a.png)
In VR they don't appear at all.

**Comment by AcChosen** [comment]
Sorry for the super late reply, but they should move by animating the pan-tilt object that is a child of the movers. The lasers you have to animate directly. But by moving the pan-tilt object, the center of the spotlights should move with them. Examples of this movement are shown in the audio link example scene. Regarding why it won't appear in VR, have you made sure that the directional light is enabled for both VR and desktop and isn't being turned off by anything?

**Comment by AcChosen** [comment]
Closing for now, please reopen with a response if the issue persists.
