### ISSUE TITLE
Declare C# namespace for VRStageLighting

### ISSUE THREAD

**Issue by Varneon** [AcChosen/VR-Stage-Lighting#9]
Namespaces are a fundamental part of C# and when authoring code for public use, it is good practice to declare a namespace for your project in order to control its scope.

Right now none of the VRStageLighting's scripts is contained in a namespace, resulting in all of them leaking to the rest of the project.

I have written a beginner guide about namespaces that could be found useful for this: https://vrclibrary.com/wiki/books/varneons-udonsharp-development-practices/page/namespaces

**Comment by AcChosen** [comment]
All scripts now belong to the "VRSL" and "VRSL.EditorScripts" namespaces as of version 2.0.1!
Thanks for the tip!
